schedule: "*/9 * * * *"
repository:
  description: desc
labels:
  - name: bug
    color: ABA000
    description: An issue with the system.
  - name: feat
    color: FFFF00
    description: An feature request
  - name: question
    color: EEEEEE
    description: An question
  
