schedule: "*/9 * * * *"
repository:
  description: yoy!
labels:
  - name: bug
    color: FFFFFF
    description: A bug

  - name: discussion
    color: FFFFFF
    description: A discussion

  - name: feature
    color: FFF111
    description: A feature

