schedule: "*/9 * * * *"
repository:
  description: yoy!
labels:
  - name: bug
    color: FFFFFF
    description: A bug

  - name: discussion
    color: FFFFFF
    description: A feature

  - name: A
    color: FFFFFF
    description: A feature
