schedule: "*/9 * * * *"
repository:
  description: yoy!
labels:
  - name: bug
    color: FFFFFF
    description: A bug

  - name: discussion
    color: FF00B0
    description: A discussion lol

  - name: refactoring
    color: FFFBBB
    description: Refactoring task

