schedule: "*/10 * * * *"
repository:
  description: alala
labels:
  - name: bugg
    color: ABA000
    description: An issue with the system.
  - name: feat
    color: FFFF00
    description: An feature request
  - name: question
    color: EEEEEE
    description: An question
  
