schedule: "*/9 * * * *"
repository:
  descripton: yoy!
labels:
  - name: bug
    color: FFFFFF
    description: A bug

  - name: discussion
    color: FF0000
    description: A discussion lol

  - name: feature!
    color: FFF111
    description: A feature

