name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: pip install and convert
        run: |
          pip install jupytext
          jupytext --to ipynb *.py
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: upload to artifact
          path: |
            *.ipynb
